### ISSUE TITLE
Spy on function that gets called 2+ times

### ISSUE THREAD

**Issue by bluemasterflows** [kiwi-bdd/Kiwi#613]
Say I have a method that I'm spying on:
KWCaptureSpy *spy = [socketMock captureArgument:@selector(on:callback:) atIndex:1];
on:callback: gets called twice with different parameters in the code i'm testing.
spy.argument only contains one block. How do I get the block from the second time on:callback: gets called?

Thanks

**Comment by bluemasterflows** [comment]
Hello?

**Comment by bluemasterflows** [comment]
helloooo?

**Comment by sharplet** [comment]
Hi! 👋🏻

Thanks for submitting a report. I apologise for the delay in responding.

What's the current behaviour your seeing for the second time the method is called? Does it fail your test? Or does it successfully capture the argument?

Also, an alternative approach could be to use `stub:withBlock:` to give you more control over what happens when the method is invoked.

Does that help at all?

**Comment by sharplet** [comment]
@modocache and I are doing some spring cleaning on issues at the moment, and this seems stale. Feel free to open a new issue if you're problem isn't resolved!
